Push initial vendor partition unlocker
Signed-off-by: Michele Beccalossi <beccalossi.michele@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,10 +1,15 @@
 #!/sbin/sh
 # AnyKernel2 Backend
 # osm0sis @ xda-developers
+#
+# Vendor Partition Unlocker
+# codeworkx @ xda-developers (original binary and scripts)
+# kylothow @ xda-developers (standalone flashable zip)
 
 OUTFD=/proc/self/fd/$2;
 ZIPFILE="$3";
-DIR=`dirname "$ZIPFILE"`;
+VENDOR=/dev/block/bootdevice/by-name/vendor;
+BLOCKDEV=/dev/block/sdf;
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -21,109 +26,80 @@ if [ ! "$(getprop 2>/dev/null)" ]; then
     test "$propval" && echo "$propval" || echo "";
   }
 fi;
-cleanup() { rm -rf /tmp/anykernel; }
-debugging() {
-  case $(basename "$ZIPFILE" .zip) in
-    *-debugging)
-      ui_print " ";
-      ui_print "Creating debugging archive in zip directory...";
-      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
-    ;;
-  esac;
-}
+cleanup() { rm -rf /tmp/vendor_unlocker; }
 abort() {
   ui_print "$*";
-  debugging;
-  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
-    cleanup;
-  fi;
+  ui_print " ";
+  cleanup;
   umount /system;
-  umount /data 2>/dev/null;
   exit 1;
+}
+safe_runcmd() {
+ cmd=$@;
+ $cmd;
+ error=$?;
+ if [ $error != 0 ]; then
+    ui_print "Error when executing command: '$command'. Aborting...";
+    abort "Error code: $error";
+ fi;
 }
 
 show_progress 1.34 4;
 ui_print " ";
 cleanup;
-mkdir -p /tmp/anykernel/bin;
-cd /tmp/anykernel;
+mkdir /tmp/vendor_unlocker;
+cd /tmp/vendor_unlocker;
 unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
+if [ $? != 0 -o -z "$(ls /tmp/vendor_unlocker/tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
-bb=/tmp/anykernel/tools/busybox;
-chmod 755 $bb;
-$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+sgdisk-op5=/tmp/vendor_unlocker/tools/sgdisk-op5;
+chmod 755 ${sgdisk-op5};
 
-ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
+ui_print "Vendor Unlocker by kylothow @ xda-developers";
 ui_print " ";
-ui_print "AnyKernel2 by osm0sis @ xda-developers";
+ui_print "Credits:"
+ui_print "  AnyKernel2 Backend by osm0sis @ xda-developers";
+ui_print "  sgdisk-op5 by codeworkx @ xda-developers";
 ui_print " ";
 umount /system 2>/dev/null;
 mount -o ro -t auto /system;
-mount -o ro -t auto /vendor 2>/dev/null;
-mount /data 2>/dev/null;
 test -f /system/system/build.prop && root=/system;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
-  for i in 1 2 3 4 5; do
-    testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
-    if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
-      ui_print "$testname";
-      match=1;
-    fi;
-  done;
-  ui_print " ";
-  if [ "$match" != 1 ]; then
-    abort "Unsupported device. Aborting...";
+ui_print "Checking device...";
+for i in 1 2 3 4; do
+  testname="$(file_getprop /tmp/vendor_unlocker/assert.prop device.name$i)";
+  if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
+    ui_print "$testname";
+    match=1;
   fi;
-fi;
-
-ui_print "Installing kernel...";
-for i in $($bb --list); do
-  $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
-fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
-if [ $? != "0" ]; then
-  abort;
+ui_print " ";
+if [ "$match" != 1 ]; then
+  abort "Unsupported device. Aborting...";
 fi;
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
+if [ ! -e "$VENDOR" ]; then
+  ui_print "Vendor partition does not exist.";
   ui_print " ";
-  ui_print "Pushing modules...";
-  mount -o rw,remount -t auto /system;
-  mount -o rw,remount -t auto /vendor 2>/dev/null;
-  cd /tmp/anykernel/modules;
-  for module in $(find . -name '*.ko'); do
-    if [ ! -e /$module ]; then
-      case $module in
-        */vendor/*) mod=vendor;;
-        *) mod=system;;
-      esac;
-    fi;
-    $bb cp -rLf $module /$module;
-    $bb chown 0:0 /$module;
-    $bb chmod 644 /$module;
-    if [ "$mod" ]; then
-      chcon "u:object_r:${mod}_file:s0" /$module;
-    fi;
-  done;
-  cd /tmp/anykernel;
-  mount -o ro,remount -t auto /system;
-  mount -o ro,remount -t auto /vendor 2>/dev/null;
+  ui_print "Using last_parti as vendor...";
+  ui_print "> Changing typecode to '8300 Linux filesystem'";
+  command="${sgdisk-op5} --typecode=6:8300 $BLOCKDEV";
+  safe_runcmd $command;
+  ui_print "> Changing name to 'vendor'"
+  command="${sgdisk-op5} --change-name=6:vendor $BLOCKDEV";
+  safe_runcmd $command;
+  ui_print " ";
+  ui_print "Vendor partition created!";
+else
+  ui_print "Found vendor partition. Good!";
 fi;
 
-debugging;
-
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
-  cleanup;
-fi;
+cleanup;
 
 umount /system;
-umount /data 2>/dev/null;
 ui_print " ";
 ui_print "Done!";
+ui_print " ";
+
+exit 0;
